name: Release

on:
  release:
    types: [published]
    branches: [ master ]

jobs:

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "frontend/package.json"

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Install frontend dependencies
        run: |
          cd frontend
          pnpm install

      - name: Build frontend
        run: |
          cd frontend
          pnpm run build

      - name: Archive frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

  build-backend:
    runs-on: ubuntu-latest
    needs: [build-frontend]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

      - name: Install backend dependencies
        run: |
          go mod download

      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

      - name: Build backend binaries with frontend
        env:
          GOOS: linux darwin windows
          GOARCH: amd64 arm64
        run: |
          mkdir -p dist
          cp -r frontend/dist public
          for os in $GOOS; do
            for arch in $GOARCH; do
              echo "Building for $os/$arch..."
              GOOS=$os GOARCH=$arch go build -o dist/myapp_${os}_${arch}
              tar -czvf dist/myapp_${os}_${arch}.tar.gz -C dist myapp_${os}_${arch}
            done
          done
          rm -rf public

      - name: Archive backend build
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: dist/*.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: [build-backend]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend-dist
          path: backend-dist

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            backend-dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
