name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sync Fork
        run: |
          git remote add upstream https://github.com/filebrowser/filebrowser.git
          git fetch upstream
          git checkout master
          git merge upstream/master
          git push origin master
